apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-api
  template:
    metadata:
      labels:
        app: profile-api
    spec:
      containers:
      - name: profile-api-container
        image: profile-api:v1
        ports:
        - containerPort: 8000
