apiVersion: v1
kind: Service
metadata:
  name: profile-api
  namespace: profile-api
spec:
  selector:
    app: profile-api
  ports:
    - protocol: TCP
      port: 3011
      targetPort: 8000
  type: NodePort
