apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-api-deployment
  namespace: profile-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-api
  template:
    metadata:
      labels:
        app: profile-api
    spec:
      containers:
      - name: profile-api-container
        image: profile-api:v1
        envFrom:
        - secretRef:
            name: profile-api-secrets
        - configMapRef:
            name: profile-api-config        
        ports:
        - containerPort: 8000

