name: Local CI/CD for Kubernetes (Self-Hosted)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: profile-api
  DEPLOYMENT_NAME: profile-api-deployment

jobs:
  build-and-deploy-local:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: |
          IMAGE_TAG="${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Load image into KIND cluster
        run: kind load docker-image ${{ env.IMAGE_TAG }}

      - name: Deploy to Kubernetes
        run: |
          echo "Updating deployment with image: ${{ env.IMAGE_TAG }}"
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.IMAGE_TAG }}
          
          # Optional: Check the rollout status to ensure it succeeds
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}

